### PR TITLE
ConCom Structure Page

### PR DESCRIPTION
**Pull request by rkaiser-dev**
This PR includes a few distinct commits which I can squash as needed.

Initial components for rendering the page with Vue components along with a couple of hooked up "composable" pieces for user permissions to support rendering, and divisions.

Also includes the loosely wired up department sidebar that simply logs when buttons on the sidebar are clicked.

This is still not hooked up on the main page yet, but if you make a couple of changes locally you can see it working.

- In `concom/admin/pages/body.inc`, add the following block starting at the first line:
```
<div id="staff-structure-app">
    <staff-structure-page></staff-structure-page>
</div>
```

- In `concom/admin/pages/head.inc` add `<script src="modules/concom/vue/StaffStructureApp.js" type="module"></script>`

No tests yet, but I can work to add those after finishing out the behavior on the sidebar. Next PR will include API changes to support saving and deleting a department/division.

### CODE REVIEW

**Comment by AricStewart** [comment]
I really like this start.  A functional close button or maybe have the + buttons not open the sidebar and I think it would be a great first step.

**Comment by rkaiser-dev** [comment]
Thanks for checking this out! I added the behavior for the Close button to close the sidebar for now.

**Comment by AricStewart** [comment]
Humm, close still not working.
I would also think you should squish a number of these commits because the patch set is doing that pet peeve of mine where it adds code in one patch and then removes/changes is dramatically in a later patch in the same set.   (especially in `modules/concom/vue/components/StaffStructureDivision.js`) If you want to squish and re-divide that is cool but you can also just squash everything now and my worries go away :)

**Comment by rkaiser-dev** [comment]
I can squash the commits, no problem.

**Comment by rkaiser-dev** [comment]
All squashed, ready to go.

**Review by AricStewart — APPROVED** [review]

**Pull request merged**
