### PR TITLE
Neon Side-by-side

### PR DESCRIPTION
**Pull request by AricStewart**

### CODE REVIEW

**Comment by AricStewart** [comment]
the eslint failure appears to be a failure with the linting tool on the size of the patch. I have linted it locally and it looks fine.

**Comment by mshappe** [comment]
I still need to get a half-hour or so to actually get this running locally. Time keeps getting away from me.

**Comment by mshappe** [comment]
I still need to get a half-hour or so to actually get this running locally. Time keeps getting away from me.

**Comment by AricStewart** [comment]
No worries.

**Comment by AricStewart** [comment]
some rework happening will resubmit later

**Pull request closed without merging**
